mail.protocol=imaps
mail.host=imap.gmail.com
mail.port=993
mail.username=????_?????@gmail.com
mail.password=???_??????_???????
mail.folder=INBOX
mail.ssl.enable=true
mail.starttls.enable=false
mail.poll.interval.seconds=30